import test from 'node:test';import assert from 'node:assert/strict';
import {IDBFactory,IDBKeyRange,IDBObjectStore} from './vendor/fake-indexeddb/esm/index.js';
import {createPhoneStore} from '../public/phone-store.js';
const factory=()=>new IDBFactory();
const store=(indexedDB=factory(),databaseName=crypto.randomUUID())=>createPhoneStore({indexedDB,IDBKeyRange,databaseName});
async function setup(s){await s.request('operator',{name:'Eryk'});const nails=await s.request('items',{name:'90mm Galvanised Nails',barcode:'5901234123457',unit:'boxes'});const timber=await s.request('items',{name:'90x45 Timber',barcode:'67890',unit:'lengths'});const job=await s.request('jobs',{client:'Caroline',name:'Fence Replacement'});return {nails:nails.id,timber:timber.id,job:job.id};}
const movement=(itemId,type,quantity,jobId=null,id=crypto.randomUUID())=>({id,itemId,type,quantity,jobId});
test('Phone storage persists records across database close/reopen and records exact Workshop/job audit snapshots',async()=>{const indexedDB=factory(),databaseName=crypto.randomUUID();let s=store(indexedDB,databaseName);const ids=await setup(s);await s.request('movements',movement(ids.nails,'STOCK_IN',4));const added=(await s.request('movements',movement(ids.nails,'STOCK_IN',3))).movement;assert.deepEqual([added.before,added.after],[4,7]);await assert.rejects(s.request('movements',movement(ids.nails,'TAKEN_TO_JOB',2)),/destination job/);const taken=(await s.request('movements',movement(ids.nails,'TAKEN_TO_JOB',2,ids.job))).movement;assert.deepEqual([taken.before,taken.after,taken.client_name,taken.job_name,taken.user_name],[7,5,'Caroline','Fence Replacement','Eryk']);await s.close();s=store(indexedDB,databaseName);const state=await s.request('state');assert.equal(state.items.find(i=>i.id===ids.nails).quantity,5);assert.equal(state.movements.length,3);assert.equal(state.user.name,'Eryk');await s.close();});
test('Phone returns maintain net materials; overdraw, excess returns and invalid input change neither stock nor history',async()=>{const s=store();const ids=await setup(s);await s.request('movements',movement(ids.timber,'STOCK_IN',30));await s.request('movements',movement(ids.timber,'TAKEN_TO_JOB',20,ids.job));const returned=(await s.request('movements',movement(ids.timber,'RETURNED_TO_WORKSHOP',4,ids.job))).movement;assert.deepEqual([returned.before,returned.after],[10,14]);for(const value of [movement(ids.timber,'RETURNED_TO_WORKSHOP',17,ids.job),movement(ids.timber,'TAKEN_TO_JOB',15,ids.job),movement(ids.timber,'TAKEN_TO_JOB',1,'missing'),movement(ids.nails,'STOCK_IN',-1),movement(ids.nails,'STOCK_IN',.5),movement(ids.nails,'STOCK_IN',1,ids.job)])await assert.rejects(s.request('movements',value));const state=await s.request('state');assert.equal(state.items.find(i=>i.id===ids.timber).quantity,14);assert.equal(state.movements.length,3);assert.equal(state.movements.filter(m=>m.job_id===ids.job).reduce((total,m)=>total+(m.type==='TAKEN_TO_JOB'?m.quantity:-m.quantity),0),16);await s.request('jobs/'+ids.job+'/status',{status:'Completed'});await assert.rejects(s.request('movements',movement(ids.timber,'TAKEN_TO_JOB',1,ids.job)),/active destination/);await s.request('movements',movement(ids.timber,'RETURNED_TO_WORKSHOP',1,ids.job));await s.close();});
test('Concurrent phone confirmations across two connections consume full stock/returns once',async()=>{const indexedDB=factory(),databaseName=crypto.randomUUID();const first=store(indexedDB,databaseName),second=store(indexedDB,databaseName);const ids=await setup(first);await first.request('movements',movement(ids.nails,'STOCK_IN',2));const take=movement(ids.nails,'TAKEN_TO_JOB',2,ids.job);const outs=await Promise.all([first.request('movements',take),second.request('movements',take)]);assert.equal(outs[0].movement.id,outs[1].movement.id);const back=movement(ids.nails,'RETURNED_TO_WORKSHOP',2,ids.job);await Promise.all([first.request('movements',back),second.request('movements',back)]);await assert.rejects(first.request('movements',{...take,quantity:1}),/already in use/);const state=await first.request('state');assert.equal(state.movements.length,3);assert.equal(state.items.find(i=>i.id===ids.nails).quantity,2);await first.close();await second.close();});
test('A failed ledger write rolls back the stock quantity and reports failure',async()=>{const s=store();const ids=await setup(s);await s.request('movements',movement(ids.nails,'STOCK_IN',7));const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args){if(this.name==='movements')throw new DOMException('Storage full','QuotaExceededError');return add.apply(this,args);};try{await assert.rejects(s.request('movements',movement(ids.nails,'TAKEN_TO_JOB',2,ids.job)),/No inventory changes were saved/);}finally{IDBObjectStore.prototype.add=add;}const state=await s.request('state');assert.equal(state.items.find(i=>i.id===ids.nails).quantity,7);assert.equal(state.movements.length,1);await s.close();});
test('Validated phone backups restore history to an empty app and reject inconsistent or destructive restores',async()=>{const source=store();const ids=await setup(source);await source.request('movements',movement(ids.nails,'STOCK_IN',7));await source.request('movements',movement(ids.nails,'TAKEN_TO_JOB',2,ids.job));await source.request('movements',movement(ids.nails,'RETURNED_TO_WORKSHOP',1,ids.job));const backup=await source.request('export');const destination=store();await destination.request('restore',backup);const state=await destination.request('state');assert.equal(state.items.find(i=>i.id===ids.nails).quantity,6);assert.equal(state.movements.length,3);assert.equal(state.user.name,'Eryk');await assert.rejects(destination.request('restore',backup),/empty phone inventory/);const invalid=structuredClone(backup);invalid.items[0].quantity=100;const empty=store();await assert.rejects(empty.request('restore',invalid),/does not match/);assert.equal((await empty.request('state')).items.length,0);await source.close();await destination.close();await empty.close();});
test('Audit snapshots survive name changes; sequence preserves chronology when the phone clock moves backward',async()=>{let timestamp='2026-10-03T08:00:00Z';const s=createPhoneStore({indexedDB:factory(),IDBKeyRange,databaseName:crypto.randomUUID(),now:()=>timestamp});const ids=await setup(s);await s.request('movements',movement(ids.nails,'STOCK_IN',7));await s.request('operator',{name:'Caroline'});timestamp='2026-10-02T08:00:00Z';await s.request('movements',movement(ids.nails,'TAKEN_TO_JOB',2,ids.job));const state=await s.request('state');assert.equal(state.movements[0].user_name,'Eryk');assert.equal(state.movements[1].user_name,'Caroline');assert.deepEqual(state.movements.map(m=>m.sequence),[1,2]);assert.ok(state.movements[0].created_at>state.movements[1].created_at);await s.close();});

test('Imported identifiers reject markup before changing any phone data',async()=>{const s=store();const backup={format:'workshop-phone-v1',items:[{id:'x"><img src=x onerror=alert(1)>',name:'Nails',barcode:'12345',unit:'boxes',quantity:0,created_at:'2026-10-03T00:00:00Z'}],jobs:[],movements:[],operator:null};await assert.rejects(s.request('restore',backup),/invalid item ID/);assert.equal((await s.request('state')).items.length,0);await s.close();});
